# Site settings
title: Zeyu Li (Zed)
email: zeyulized@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username: Zedli123

# Build settings
markdown: kramdown
